# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aecc9e8e2c273f09813c4f09d3ab9b26cf8f95b829d929091ef98ab2883e73f6f9e337cfa542cfa44f79da056eb7be9091287e6238a63af80eddbbbcab95aeff

test:
  secret_key_base: 659c2d5468a478df684b8044b7e0919062c6befb0a88e878723600824217f51b1660fd98ea746943cff3447f948310af3fab25305780791b9d7c53c9e26141fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
